on:
  schedule:
    - cron: '*/30 00-01 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: refresh-data

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: install pak
        run: Rscript -e 'install.packages("pak")'

      - name: install packages
        run: Rscript -e 'pak::pak(c("ropensci/bowerbird", "AustralianAntarcticDivision/blueant", "fs", "here")); source("data-raw/run.R", echo = TRUE)'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit
        run: |
          git config --global user.name 'Michael Sumner'
          git config --global user.email 'mdsumner@gmail.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
